# Generated by Django 3.2.8 on 2021-10-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_INVENTORY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assignedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='officeLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC_INVENTORY.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC_INVENTORY.vendor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='officeLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC_INVENTORY.location'),
        ),
    ]
