# Generated by Django 3.2.8 on 2021-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_INVENTORY', '0002_auto_20211027_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
