# Generated by Django 3.2.8 on 2021-10-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_INVENTORY', '0004_auto_20211023_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
