# Generated by Django 3.2.8 on 2021-10-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_INVENTORY', '0007_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
