# Generated by Django 3.2.8 on 2021-10-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_INVENTORY', '0008_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='officeLocation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='officeLocation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
