# Generated by Django 3.2.8 on 2021-10-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_INVENTORY', '0009_auto_20211026_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='officeLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC_INVENTORY.location'),
        ),
    ]
